services:
  mariadb_auth:
    image: mariadb
    container_name: mariadb_auth
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: gouser
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: go_auth
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb_auth
      PMA_USER: gouser
      PMA_PASSWORD: password
    ports:
      - '8080:80'
    depends_on:
      - mariadb_auth