services:
  mariadb_training:
    image: mariadb
    container_name: mariadb_training
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: gouser
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: go_training
    ports:
      - '3308:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_training
    environment:
      PMA_HOST: mariadb_training
      PMA_USER: gouser
      PMA_PASSWORD: password
    ports:
      - '8080:80'
    depends_on:
      - mariadb_training