CREATE TABLE IF NOT EXISTS CONTENT_AND_SCHEDULES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    day_number INT DEFAULT 1,
    duration VARCHAR(255),
    description TEXT,
    content TEXT,
    is_practical BOOLEAN DEFAULT FALSE,
    resources_required TEXT,
    order_position INT DEFAULT 0,
    training_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (training_id) REFERENCES TRAININGS(id) ON DELETE CASCADE
)
