CREATE TABLE IF NOT EXISTS TRAINING_RESERVATIONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    training_id INT NOT NULL,
    user_id CHAR(36) NOT NULL,
    stripe_session_id VARCHAR(255) NOT NULL UNIQUE,
    amount_cents INT NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
